version: "3.9"

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.1.0/24"

services:
  alpine1:
    image: alpine
    container_name: alpine1
    tty: true
    networks:
      net:
        ipv4_address: 172.16.1.6

  alpine2:
    image: alpine
    container_name: alpine2
    tty: true
    networks:
      net:
        ipv4_address: 172.16.1.7

  alpine3:
    image: alpine
    container_name: alpine3
    tty: true
    networks:
      net:
        ipv4_address: 172.16.1.8

  alpine4:
    image: alpine
    container_name: alpine4
    tty: true
    networks:
      net:
        ipv4_address: 172.16.1.9
