services:
  postgres:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
        #volumes:
      #- db_data:/var/lib/postgresql/data
      #- ./initdb:/docker-entrypoint-initdb.d
    restart: always

#volumes:
#  db_data:
