CREATE TABLE IF NOT EXISTS container (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR NOT NULL,
	ip INET UNIQUE NOT NULL,
	status VARCHAR NOT NULL DEFAULT 'unknown',
	version INT NOT NULL DEFAULT 1,
	ping INT NOT NULL DEFAULT 0,
	--updated_at TIMESTAMP NOT NULL DEFAULT to_timestamp(0)
        updated_at TIMESTAMP
);
